name: ecoach
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.6+23

environment:
   sdk: '>=2.12.0 <3.0.0'

dependencies:
   flutter:
      sdk: flutter
   flutter_native_splash: ^2.0.1+1
   provider: ^6.0.1
   http: ^0.13.3
   shared_preferences: ^2.0.7
   sqflite: ^2.0.0+3
   path_provider: ^2.0.2
   validators: ^3.0.0
   datetime_picker_formfield: ^2.0.0
   cached_network_image: ^3.1.0
   image_picker: ^0.8.3+3
   flutter_svg: ^1.0.3 # help us to use SVG in our app
   # file_picker_cross: ^4.2.6
   get: ^4.3.8
   flutter_tex: ^4.0.3+1
   pin_code_fields: ^7.3.0
   webview_flutter: ^2.0.6
   intl_phone_field: ^3.0.1
   flutter_html: ^3.0.0-alpha.2
   flutter_html_table: ^3.0.0-alpha.2
   percent_indicator: ^4.0.0
   scrollable_positioned_list: ^0.3.2
   google_fonts: ^2.1.0
   flutter_math_fork: ^0.6.1
   carousel_slider: ^4.0.0
   signal_strength_indicator: ^0.4.1
   fl_chart: ^0.41.0
   wakelock: ^0.6.1+1
   flutter_local_notifications: ^9.0.1
   basic_utils: ^4.0.1
   change_app_package_name: ^1.0.0
   another_xlider: ^1.0.0
   stop_watch_timer: ^1.3.1
   simple_timer: ^2.0.0
   web_socket_channel: ^2.1.0

   cupertino_icons: ^1.0.3
   intl: ^0.17.0
   # catex: ^0.0.1+8
   custom_timer: ^0.1.1
   timeago: ^3.1.0
   dio: ^4.0.0
   permission_handler: ^8.3.0
   flutter_styled_toast: ^2.0.0
   accordion: ^2.1.2
   timer_count_down: ^2.2.1
   internet_connection_checker: ^0.0.1+3
   phone_form_field: ^6.0.0
   hexcolor: ^2.0.6
   flutter_screenutil: ^5.5.3+1
   google_sign_in: ^5.3.2
   package_info_plus: ^1.4.2
   flutter_flavor: ^3.0.3

   # firebase_core: ^1.16.0
   # firebase_auth: ^3.3.17
   fluttertoast: ^8.0.6
   page_transition: ^2.0.2
   recase: ^4.0.0
   flutter_staggered_grid_view: ^0.4.0
   url_launcher: ^6.0.10
   linkfy_text: ^1.1.5
   flutter_linkify: ^5.0.2
   flutter_switch: ^0.3.2
   flutter_countdown_timer: ^4.1.0
   number_paginator: ^0.0.2
   responsive_sizer: ^3.0.8
   pinput: ^2.2.10
   country_picker: ^2.0.15
   google_mobile_ads: ^1.3.0
   slide_to_confirm: ^1.1.0
   flutter_pin_code_fields: ^1.1.0
   otp_pin_field: ^1.0.1

flutter_icons:
   image_path: "assets/images/adeo_app_icon.png"
   android: true
   ios: true

dev_dependencies:
   flutter_launcher_icons: ^0.9.1
   flutter_test:
      sdk: flutter

   flutter_lints: ^1.0.0

flutter:
   uses-material-design: true

   assets:
      - assets/flags/
      - assets/fonts/
      - assets/images/
      - assets/images/notes/
      - assets/images/learn_module/
      - assets/icons/
      - assets/icons/navigation/
      - assets/icons/arrows/
      - assets/icons/topics/
      - assets/icons/courses/
      - assets/icons/subscriptions/
      - assets/onboard/
      - assets/review/

   fonts:
      - family: 'Poppins'
        fonts:
           - asset: assets/fonts/Poppins-Regular.ttf
           - asset: assets/fonts/Poppins-ExtraLight.ttf
             weight: 200
           - asset: assets/fonts/Poppins-Medium.ttf
             weight: 500
           - asset: assets/fonts/Poppins-SemiBold.ttf
             weight: 600
           - asset: assets/fonts/Poppins-Bold.ttf
             weight: 700
      - family: 'Hamelin'
        fonts:
           - asset: assets/fonts/Hamelin.ttf
      - family: 'Helvetica Rounded'
        fonts:
           - asset: assets/fonts/HelveticaRoundedLTStd-Bd.otf
      - family: "WorkSans"
        fonts:
           - asset: assets/fonts/WorkSans-Regular.ttf
           - asset: assets/fonts/WorkSans-Medium.ttf
             weight: 500
           - asset: assets/fonts/WorkSans-SemiBold.ttf
             weight: 600
           - asset: assets/fonts/WorkSans-Bold.ttf
             weight: 700
      - family: "Roboto"
        fonts:
           - asset: assets/fonts/Roboto-Bold.ttf
           - asset: assets/fonts/Roboto-Regular.ttf
           - asset: assets/fonts/Roboto-Medium.ttf
             weight: 400
      - family: "Cocon"
        fonts:
           - asset: assets/fonts/COCON-BOLD-FONT.OTF
           - asset: assets/fonts/COCON-REGULARTR.TTF
      - family: "Helvetica"
        fonts:
           - asset: assets/fonts/HELVETICAROUNDEDLTSTD-BD.OTF
           - asset: assets/fonts/HELVETICAROUNDEDLTSTD-BDCN.OTF
           - asset: assets/fonts/HELVETICAROUNDEDLTSTD-BLACK.OTF

